spring:
  application:
    name: feedbackhub

  profiles:
    active: ${SPRING_PROFILE:cloud}

  datasource:
    url: ${DB_URL:jdbc:sqlserver://feedbackhub-server-55878.database.windows.net:1433;database=feedbackhub;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;}
    username: ${DB_USERNAME:azureuser}
    password: ${DB_PASSWORD:FeedbackHub@2026!}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

# SendGrid Email Service
azure:
  sendgrid:
    api-key: ${SENDGRID_API_KEY}
    from-email: ${SENDGRID_FROM_EMAIL:noreply@seudominio.com}
    from-name: ${SENDGRID_FROM_NAME:FeedbackHub}

  storage:
    connection-string: ${AZURE_STORAGE_CONNECTION_STRING}
    queue:
      urgencia-name: ${AZURE_QUEUE_NAME:feedback-urgencia-queue}

  email:
    admin-recipients: ${ADMIN_EMAILS:leonart16@gmail.com}
    report-recipients: ${REPORT_EMAILS:leonart16@gmail.com}

# Configurações de Feedback
feedback:
  urgencia:
    critica:
      nota-maxima: 3
    media:
      nota-maxima: 6

# Configurações de Relatórios
relatorio:
  semanal:
    titulo: "FeedbackHub - Relatório Semanal de Avaliações"
    diasRetroativos: 7

# Logging
logging:
  level:
    root: INFO
    com.fiap.feedbackhub: DEBUG
    com.azure: ERROR
    com.azure.communication: ERROR
    com.azure.core: ERROR
    com.azure.storage: ERROR
    reactor.netty: ERROR
    io.netty: ERROR
    org.hibernate: WARN

